### ISSUE TITLE
Update python required version to 3.10

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#64]
Reported bug with the csv loading ([see here](https://moosvilab.ok.ubc.ca/moosvilab/pl/cna8b9jwtjr37bxbe6i57gtzxo) for details)

```
$ python checkq.py "C:\Users\Zecr\Offline Storage\Software Development\OPB\instructor_datascience_bank\source\python2\function_output_4\Function Output 4.md"
Traceback (most recent call last):
  File "C:\Users\Zecr\miniconda3\lib\importlib\resources.py", line 97, in open_binary
    return open(full_path, mode='rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Zecr\\Offline Storage\\Software Development\\OPB\\instructor_datascience_bank\\scripts\\animals.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zecr\Offline Storage\Software Development\OPB\instructor_datascience_bank\scripts\checkq.py", line 17, in <module>
    import problem_bank_scripts as pbs
  File "C:\Users\Zecr\miniconda3\lib\site-packages\problem_bank_scripts\__init__.py", line 3, in <module>
    from .problem_bank_scripts import *
  File "C:\Users\Zecr\miniconda3\lib\site-packages\problem_bank_scripts\problem_bank_scripts.py", line 20, in <module>
    import problem_bank_helpers as pbh
  File "C:\Users\Zecr\miniconda3\lib\site-packages\problem_bank_helpers\__init__.py", line 3, in <module>
    from .problem_bank_helpers import *
  File "C:\Users\Zecr\miniconda3\lib\site-packages\problem_bank_helpers\problem_bank_helpers.py", line 15, in <module>
    with importlib.resources.open_text("problem_bank_helpers.data", "animals.csv") as file:
  File "C:\Users\Zecr\miniconda3\lib\importlib\resources.py", line 121, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
  File "C:\Users\Zecr\miniconda3\lib\importlib\resources.py", line 111, in open_binary
    raise FileNotFoundError(message)
FileNotFoundError: 'animals.csv' resource not found in 'problem_bank_helpers.data'
```

One potential fix is to require python 3.10 (though this is unconfirmed).

**Comment by firasm** [comment]
**Update: confirmed the problem is fixed by python 3.10**
